Web/Vxp.Web/Areas/Customer/Controllers/ProductsController.cs
namespace Vxp.Web.Areas.Customer.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Linq;
    using System.Threading.Tasks;
    using Vxp.Services.Data.Products;
    using Vxp.Data.Common.Enums;
    using Services.Models;
    using Vxp.Web.ViewModels.Customer.Products;

    public class ProductsController : CustomersController
    {
        private readonly IProductsService _productsService;
        private readonly IProductPricesService _productPricesService;

        public ProductsController(
            IProductsService productsService,
            IProductPricesService productPricesService)
        {
            this._productsService = productsService;
            this._productPricesService = productPricesService;
        }

        public async Task<IActionResult> Index(int categoryId)
        {
            var products = this._productsService.GetAllProducts<ProductListViewModel>().Where(p => p.IsAvailable);
            if (categoryId > 0)
            {
                products = products.Where(p => p.CategoryId == categoryId);
            }

            var viewModel = new ProductsListViewModel
            {
                CategoryFilterId = categoryId,
                Products = await products.ToListAsync()
            };

            return View(viewModel);
        }

        public IActionResult Product(int id)
        {
            var product = this._productsService.GetAllProducts<ProductViewModel>().FirstOrDefault(p => p.Id == id);
            if (product == null)
            {
                return this.RedirectToAction(nameof(this.Index));
            }

            var priceModifiers =
                this._productPricesService.GetBuyerPriceModifiers<PriceModifierDto>(this.User.Identity.Name);

            foreach (var priceModifier in priceModifiers)
            {
                var priceModel = AutoMapper.Mapper.Map<ProductPriceViewModel>(priceModifier);

                if (priceModifier.PriceModifierType == PriceModifierType.Decrease)
                {
                    priceModel.Price = product.BasePrice - (product.BasePrice * priceModifier.PercentValue / 100);
                }
                else
                {
                    priceModel.Price = product.BasePrice + (product.BasePrice * priceModifier.PercentValue / 100);
                }
                product.Prices.Add(priceModel);
            }

            product.Images.Insert(0, product.Image);

            return this.View(product);
        }
    }
}

Web/Vxp.Web/Areas/Distributor/Controllers/ProductsController.cs
namespace Vxp.Web.Areas.Distributor.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Vxp.Services.Data.Products;
    using Vxp.Web.ViewModels.Distributor.Products;
    using Services.Models;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.EntityFrameworkCore;

    public class ProductsController : DistributorsController
    {
        private readonly IProductsService _productsService;
        private readonly IProductPricesService _productPricesService;

        public ProductsController(
            IProductsService productsService,
            IProductPricesService productPricesService)
        {
            this._productsService = productsService;
            this._productPricesService = productPricesService;
        }

        public async Task<IActionResult> Index(int categoryId)
        {
            var priceModifier =
                this._productPricesService.GetBuyerPriceModifiers<PriceModifierDto>(this.User.Identity.Name).FirstOrDefault() ??
                new PriceModifierDto();


            var products = this._productsService.GetAllProducts<ProductListViewModel>().Where(p => p.IsAvailable);
            if (categoryId > 0)
            {
                products = products.Where(p => p.CategoryId == categoryId);
            }

            var viewModel = new ProductsListViewModel
            {
                CategoryFilterId = categoryId,
                Products = await products.ToListAsync()
            };

            foreach (var productListViewModel in viewModel.Products)
            {
                productListViewModel.ModifierValue = priceModifier.PercentValue;
                productListViewModel.PriceModifierType = priceModifier.PriceModifierType;
            }

            return View(viewModel);
        }

        public IActionResult Product(int id)
        {
            var product =
                this._productsService.GetAllProducts<ProductViewModel>().FirstOrDefault(p => p.Id == id);

            if (product == null)
            {
                return this.RedirectToAction(nameof(this.Index));
            }

            var priceModifier =
                this._productPricesService.GetBuyerPriceModifiers<PriceModifierDto>(this.User.Identity.Name)
                .FirstOrDefault() ?? new PriceModifierDto();

            product.PriceModifierType = priceModifier.PriceModifierType;
            product.ModifierValue = priceModifier.PercentValue;

            product?.Images.Insert(0, product.Image);

            return this.View(product);
        }
    }
}

Web/Vxp.Web/Controllers/DistributorsController.cs
namespace Vxp.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.EntityFrameworkCore;
    using Common;
    using Vxp.Services.Data.Users;
    using ViewModels.Users;
    using Vxp.Services.Data.BankAccounts;
    using Services.Models;
    using ViewModels.Distributor;

    public class DistributorsController : ApiController
    {
        private readonly IUsersService _usersService;
        private readonly IDistributorsService _distributorsService;
        private readonly IBankAccountsService _bankAccountsService;

        public DistributorsController(
            IUsersService usersService, 
            IDistributorsService distributorsService, 
            IBankAccountsService bankAccountsService)
        {
            this._usersService = usersService;
            this._distributorsService = distributorsService;
            this._bankAccountsService = bankAccountsService;
        }

        [HttpGet("[action]/{customerName}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<string>> GetAvailable(string customerName)
        {

            var usrDistributors = this._distributorsService
                .GetDistributorsForUserAsync<UserProfileDistributorViewModel>(customerName).GetAwaiter().GetResult().Select(u => u.UserName).ToHashSet();

            var allDistributors = await this._usersService
                .GetAllInRoleAsync<UserProfileDistributorViewModel>(GlobalConstants.Roles
                    .DistributorRoleName);

            var availableDistributors = await allDistributors
                    .Where(d => !usrDistributors.Contains(d.UserName))
                    .Where(d => d.UserName != customerName)
                    .ToArrayAsync();

            return this.Ok(availableDistributors);
        }

        [HttpGet("{id}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<string>> Get(string id)
        {
            var distributors = await
                this._usersService.GetAll<UserProfileDistributorViewModel>(d => d.Id == id);

            if (!distributors.Any())
            {
                return this.BadRequest();
            }

            return this.Ok(distributors);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Connect(DistributorConnectInputModel inputModel)
        {
            if (this.ModelState.IsValid)
            {
                var distributorKey = this._distributorsService.GenerateNewKeyForDistributor(inputModel.DistributorEmail);
                var bankAccount = this._bankAccountsService
                    .GetBankAccountsForUser<BankAccountDto>(inputModel.DistributorEmail).FirstOrDefault();
                if (bankAccount == null)
                {
                    return this.BadRequest();
                }

                await this._bankAccountsService.AssignDistributorKeyToBankAccountAsync(bankAccount.Id, distributorKey);

                if (await this._distributorsService.AddCustomerToDistributorAsync(inputModel.CustomerEmail, distributorKey))
                {
                    return this.Ok();
                }
            }
            return this.BadRequest();
        }

        [HttpPost("[action]")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Disconnect(DistributorConnectInputModel inputModel)
        {
            if (this.ModelState.IsValid)
            {
                if (await this._distributorsService.RemoveCustomerFromDistributorAsync(inputModel.CustomerEmail, inputModel.DistributorEmail))
                {
                    return this.Ok();
                }
            }
            return this.BadRequest();
        }

    }
}

Web/Vxp.Web/ViewComponents/ProductCategoryFilterViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Vxp.Data.Common.Repositories;
using Vxp.Data.Models;
using Vxp.Services.Mapping;

namespace Vxp.Web.ViewComponents
{
    public class ProductCategoryFilterViewComponent : ViewComponent
    {
        private readonly IDeletableEntityRepository<ProductCategory> _productCategoriesRepository;
        public ProductCategoryFilterViewComponent(IDeletableEntityRepository<ProductCategory> productCategoriesRepository)
        {
            this._productCategoriesRepository = productCategoriesRepository;
        }

        public IViewComponentResult Invoke(int categoryId)
        {
            var categories = this._productCategoriesRepository.AllAsNoTracking().To<SelectListItem>().ToList();
            categories.Add(new SelectListItem("- All -", "0"));
            foreach (var selectListItem in categories
                .Where(selectListItem => selectListItem.Value == categoryId.ToString()))
            {
                selectListItem.Selected = true;
                break;
            }

            return this.View(categories);
        }

    }
}

Web/Vxp.Web/Areas/Customer/Views/Products/Index.cshtml
@using System.Web
@model Vxp.Web.ViewModels.Customer.Products.ProductsListViewModel
@{
    ViewData["Title"] = "Products";
}

<div class="w-33 mb-3 d-flex justify-content-between">
    <h4>@ViewData["Title"]</h4>
    <div class="px-4"></div>
    <vc:product-category-filter category-id="@Model.CategoryFilterId"></vc:product-category-filter>
</div>
<div class="row">
    @Html.AntiForgeryToken()
    @foreach (var product in Model.Products)
    {
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-3">
            <div class="card h-100">
                <span class="vxp-card-order-add icon icon-shopping-basket" title="Add to order" onclick="addToOrder(@product.Id)"></span>
                <a asp-controller="Products" asp-action="Product" asp-route-id="@product.Id">
                    <div class="card-img-top zoom">
                        <img src="@HttpUtility.UrlDecode(product.Image.Url)" alt="@product.Image.Alt" title="@product.Image.Title">
                    </div>
                </a>
                <div class="card-body text-center h-25 pb-0 pt-0 pl-0 pr-0">
                    <div class="pb-1 mt-1">
                        <span class="mx-auto pb-1 text-dark font-weight-bold">@product.Name</span>
                    </div>
                    <div>
                        @product.Description
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Web/Vxp.Web/Areas/Customer/Views/Products/Product.cshtml
@using System.Web
@model Vxp.Web.ViewModels.Customer.Products.ProductViewModel
@{
    ViewData["Title"] = @Model.Name;
}
<h4>@ViewData["Title"]</h4>
<div class="d-flex">
    <div class="row w-50">
        @foreach (var image in @Model.Images)
        {
            <div class="col-6 col-sm-6 col-md-6 col-lg-6 mb-3 pl-0">
                <div class="card zoom">
                    <a href="@HttpUtility.UrlDecode(image.Url)" class="image-popup">
                        <div class="card-body text-center p-1">
                            <img src="@HttpUtility.UrlDecode(image.Url)" alt="@image.Alt" title="@image.Title">
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>
    <div class="w-50 pb-3">
        <div class="border rounded h-100 px-1">
            <div class="row">
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 font-small my-auto">Category</div>
                <div class="col text-dark">@Model.CategoryName</div>
            </div>
            <div class="row bg-light">
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 font-small my-auto">Description</div>
                <div class="col text-dark">@Model.Description</div>
            </div>
            @for (var i = 0; i < @Model.Details.Count; i++)
            {
                var detail = @Model.Details[i];
                var bgLight = i % 2 > 0 ? "bg-light" : "";
                <div class="row @bgLight">
                    <div class="col-6 col-sm-6 col-md-6 col-lg-3 font-small my-auto">@detail.CommonDetail.Name@(string.IsNullOrEmpty(detail.CommonDetail.Measure) ? "" : $", {detail.CommonDetail.Measure}")</div>
                    <div class="col text-dark">@detail.Value</div>
                </div>
            }
            <div class="row bg-secondary rounded text-white px-2">Prices</div>
            @for (var i = 0; i < Model.Prices.Count; i++)
            {
                var price = Model.Prices[i];
                var bgLight = i % 2 > 0 ? "bg-light" : "";
                <div class="row @bgLight">
                    <div class="col-6 col-sm-6 col-md-6 col-lg-3 font-weight-bold my-auto">
                        <a asp-area="Customer" asp-controller="Distributors" asp-action="Distributor" asp-route-id="@price.SellerId" title="Preview">@price.SellerName</a>
                    </div>
                    <div class="col text-dark">€ @price.PriceFormatted</div>
                </div>
            }
        </div>
    </div>
</div>

Web/Vxp.Web/Areas/Customer/Views/Products/View.cshtml
@using System.Web
@model Vxp.Web.ViewModels.Customers.Products.ProductViewModel
@{
    ViewData["Title"] = @Model.Name;
}
<h4>@ViewData["Title"]</h4>
<div class="d-flex">
    <div class="row w-50">
        @foreach (var image in @Model.Images)
        {
            <div class="col-6 col-sm-6 col-md-6 col-lg-6 mb-3 pl-0">
                <div class="card zoom">
                    <a href="@HttpUtility.UrlDecode(image.Url)" class="image-popup">
                        <div class="card-body text-center p-1">
                            <img src="@HttpUtility.UrlDecode(image.Url)" alt="@image.Alt" title="@image.Title">
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>
    <div class="w-50 pb-3">
        <div class="border rounded h-100 px-1">
            <div class="row">
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 font-small my-auto">Category</div>
                <div class="col text-dark">@Model.CategoryName</div>
            </div>
            <div class="row bg-light">
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 font-small my-auto">Description</div>
                <div class="col text-dark">@Model.Description</div>
            </div>
            @for (var i = 0; i < @Model.Details.Count; i++)
            {
                var detail = @Model.Details[i];
                var bgLight = i % 2 > 0 ? "bg-light" : "";
                <div class="row @bgLight">
                    <div class="col-6 col-sm-6 col-md-6 col-lg-3 font-small my-auto">@detail.CommonDetail.Name@(string.IsNullOrEmpty(detail.CommonDetail.Measure) ? "" : $", {detail.CommonDetail.Measure}")</div>
                    <div class="col text-dark">@detail.Value</div>
                </div>
            }
        </div>
    </div>
</div>